//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18063
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GMCOffer.SampleMetrics {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://samplemetrics-api.safeprocessing.com/pii", ConfigurationName="SampleMetrics.piiSoap")]
    public interface piiSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://samplemetrics-api.safeprocessing.com/pii/GetShippingStatus", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        GMCOffer.SampleMetrics.ShippingStatus GetShippingStatus(string InventoryID, int OrderNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://samplemetrics-api.safeprocessing.com/pii/GetCurrentInventory", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int GetCurrentInventory(string InventoryID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://samplemetrics-api.safeprocessing.com/pii/GetCurrentSKUInventory", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        GMCOffer.SampleMetrics.SampleSKU[] GetCurrentSKUInventory(string InventoryID, string Sku);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://samplemetrics-api.safeprocessing.com/pii/AddressValidation", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        GMCOffer.SampleMetrics.AddressResult AddressValidation(string MailingStreetAddress1, string MailingStreetAddress2, string MailingCity, string MailingState, string MailingPostalCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://samplemetrics-api.safeprocessing.com/pii/Submit", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        GMCOffer.SampleMetrics.Results Submit(
                    string InventoryID, 
                    string Source, 
                    string AccessKey, 
                    string TrafficSource, 
                    string RegistrationSource, 
                    string FirstName, 
                    string LastName, 
                    string MailingStreetAddress1, 
                    string MailingStreetAddress2, 
                    string MailingCity, 
                    string MailingState, 
                    string MailingPostalCode, 
                    string MailingCountry, 
                    string EmailAddress, 
                    string Gender, 
                    string Birthdate, 
                    string CCGSKU, 
                    string Opt1, 
                    string Opt2, 
                    string Opt3, 
                    string Opt4, 
                    string Additional1, 
                    string Additional2, 
                    string Additional3, 
                    string Additional4, 
                    string Additional5, 
                    string Additional6, 
                    string Additional7, 
                    string Additional8, 
                    string Additional9, 
                    string Additional10, 
                    string Additional11, 
                    string Additional12, 
                    string Additional13, 
                    string Additional14, 
                    string Additional15, 
                    string Additional16, 
                    string Additional17, 
                    string Additional18, 
                    string Additional19, 
                    string Additional20, 
                    string Additional21, 
                    string Additional22, 
                    string Additional23, 
                    string Additional24, 
                    string Additional25, 
                    string UserAgent, 
                    string IsRequiredBirthDate, 
                    string IsRequiredEmail, 
                    string IsRequiredAddressValidation);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://samplemetrics-api.safeprocessing.com/pii")]
    public partial class ShippingStatus : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string trackingNumberField;
        
        private string statusField;
        
        private WebServiceError[] errorsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string TrackingNumber {
            get {
                return this.trackingNumberField;
            }
            set {
                this.trackingNumberField = value;
                this.RaisePropertyChanged("TrackingNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("Status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=2)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Error")]
        public WebServiceError[] Errors {
            get {
                return this.errorsField;
            }
            set {
                this.errorsField = value;
                this.RaisePropertyChanged("Errors");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://samplemetrics-api.safeprocessing.com/pii")]
    public partial class WebServiceError : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codeField;
        
        private string messageField;
        
        private Address[] additionalField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("Code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("Message");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=2)]
        public Address[] Additional {
            get {
                return this.additionalField;
            }
            set {
                this.additionalField = value;
                this.RaisePropertyChanged("Additional");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://samplemetrics-api.safeprocessing.com/pii")]
    public partial class Address : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string address1Field;
        
        private string address2Field;
        
        private string cityField;
        
        private string stateField;
        
        private string zipField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Address1 {
            get {
                return this.address1Field;
            }
            set {
                this.address1Field = value;
                this.RaisePropertyChanged("Address1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Address2 {
            get {
                return this.address2Field;
            }
            set {
                this.address2Field = value;
                this.RaisePropertyChanged("Address2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string City {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
                this.RaisePropertyChanged("City");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string State {
            get {
                return this.stateField;
            }
            set {
                this.stateField = value;
                this.RaisePropertyChanged("State");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Zip {
            get {
                return this.zipField;
            }
            set {
                this.zipField = value;
                this.RaisePropertyChanged("Zip");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://samplemetrics-api.safeprocessing.com/pii")]
    public partial class Results : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool successfulField;
        
        private int orderNumberField;
        
        private WebServiceError[] errorsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public bool Successful {
            get {
                return this.successfulField;
            }
            set {
                this.successfulField = value;
                this.RaisePropertyChanged("Successful");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int OrderNumber {
            get {
                return this.orderNumberField;
            }
            set {
                this.orderNumberField = value;
                this.RaisePropertyChanged("OrderNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=2)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Error")]
        public WebServiceError[] Errors {
            get {
                return this.errorsField;
            }
            set {
                this.errorsField = value;
                this.RaisePropertyChanged("Errors");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://samplemetrics-api.safeprocessing.com/pii")]
    public partial class AddressResult : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool validField;
        
        private Address mailingAddressField;
        
        private WebServiceError[] errorsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public bool Valid {
            get {
                return this.validField;
            }
            set {
                this.validField = value;
                this.RaisePropertyChanged("Valid");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public Address MailingAddress {
            get {
                return this.mailingAddressField;
            }
            set {
                this.mailingAddressField = value;
                this.RaisePropertyChanged("MailingAddress");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=2)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Error")]
        public WebServiceError[] Errors {
            get {
                return this.errorsField;
            }
            set {
                this.errorsField = value;
                this.RaisePropertyChanged("Errors");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://samplemetrics-api.safeprocessing.com/pii")]
    public partial class SampleSKU : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string sKUField;
        
        private string sampleDescriptionField;
        
        private string balanceOnHandField;
        
        private bool activeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string SKU {
            get {
                return this.sKUField;
            }
            set {
                this.sKUField = value;
                this.RaisePropertyChanged("SKU");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string SampleDescription {
            get {
                return this.sampleDescriptionField;
            }
            set {
                this.sampleDescriptionField = value;
                this.RaisePropertyChanged("SampleDescription");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string BalanceOnHand {
            get {
                return this.balanceOnHandField;
            }
            set {
                this.balanceOnHandField = value;
                this.RaisePropertyChanged("BalanceOnHand");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public bool Active {
            get {
                return this.activeField;
            }
            set {
                this.activeField = value;
                this.RaisePropertyChanged("Active");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface piiSoapChannel : GMCOffer.SampleMetrics.piiSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class piiSoapClient : System.ServiceModel.ClientBase<GMCOffer.SampleMetrics.piiSoap>, GMCOffer.SampleMetrics.piiSoap {
        
        public piiSoapClient() {
        }
        
        public piiSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public piiSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public piiSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public piiSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public GMCOffer.SampleMetrics.ShippingStatus GetShippingStatus(string InventoryID, int OrderNumber) {
            return base.Channel.GetShippingStatus(InventoryID, OrderNumber);
        }
        
        public int GetCurrentInventory(string InventoryID) {
            return base.Channel.GetCurrentInventory(InventoryID);
        }
        
        public GMCOffer.SampleMetrics.SampleSKU[] GetCurrentSKUInventory(string InventoryID, string Sku) {
            return base.Channel.GetCurrentSKUInventory(InventoryID, Sku);
        }
        
        public GMCOffer.SampleMetrics.AddressResult AddressValidation(string MailingStreetAddress1, string MailingStreetAddress2, string MailingCity, string MailingState, string MailingPostalCode) {
            return base.Channel.AddressValidation(MailingStreetAddress1, MailingStreetAddress2, MailingCity, MailingState, MailingPostalCode);
        }
        
        public GMCOffer.SampleMetrics.Results Submit(
                    string InventoryID, 
                    string Source, 
                    string AccessKey, 
                    string TrafficSource, 
                    string RegistrationSource, 
                    string FirstName, 
                    string LastName, 
                    string MailingStreetAddress1, 
                    string MailingStreetAddress2, 
                    string MailingCity, 
                    string MailingState, 
                    string MailingPostalCode, 
                    string MailingCountry, 
                    string EmailAddress, 
                    string Gender, 
                    string Birthdate, 
                    string CCGSKU, 
                    string Opt1, 
                    string Opt2, 
                    string Opt3, 
                    string Opt4, 
                    string Additional1, 
                    string Additional2, 
                    string Additional3, 
                    string Additional4, 
                    string Additional5, 
                    string Additional6, 
                    string Additional7, 
                    string Additional8, 
                    string Additional9, 
                    string Additional10, 
                    string Additional11, 
                    string Additional12, 
                    string Additional13, 
                    string Additional14, 
                    string Additional15, 
                    string Additional16, 
                    string Additional17, 
                    string Additional18, 
                    string Additional19, 
                    string Additional20, 
                    string Additional21, 
                    string Additional22, 
                    string Additional23, 
                    string Additional24, 
                    string Additional25, 
                    string UserAgent, 
                    string IsRequiredBirthDate, 
                    string IsRequiredEmail, 
                    string IsRequiredAddressValidation) {
            return base.Channel.Submit(InventoryID, Source, AccessKey, TrafficSource, RegistrationSource, FirstName, LastName, MailingStreetAddress1, MailingStreetAddress2, MailingCity, MailingState, MailingPostalCode, MailingCountry, EmailAddress, Gender, Birthdate, CCGSKU, Opt1, Opt2, Opt3, Opt4, Additional1, Additional2, Additional3, Additional4, Additional5, Additional6, Additional7, Additional8, Additional9, Additional10, Additional11, Additional12, Additional13, Additional14, Additional15, Additional16, Additional17, Additional18, Additional19, Additional20, Additional21, Additional22, Additional23, Additional24, Additional25, UserAgent, IsRequiredBirthDate, IsRequiredEmail, IsRequiredAddressValidation);
        }
    }
}
